export const AUTH = "AUTH";
export const SAVE = "SAVE";
export const LOGOUT = "LOGOUT";

export const CREATE = "CREATE";
export const DELETE = "DELETE";
export const FETCH = "FETCH";
export const UPDATE = "UPDATE";
export const FETCH_ONE = "FETCH_ONE";
export const FETCH_ALL = "FETCH_ALL";

export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";

export const BTN_LOADING_START = "BTN_LOADING_START";
export const BTN_LOADING_END = "BTN_LOADING_END";

export const DELETE_BTN_LOAD_START = "DELETE_BTN_LOAD_START";
export const DELETE_BTN_LOAD_END = "DELETE_BTN_LOAD_END"; 


export const CREATE_MAIN_AREA = "CREATE_MAIN_AREA";
export const FETCH_ALL_MAIN_AREA = "FETCH_ALL_MAIN_AREA";

export const FETCH_ALL_PRODUCT_GROUP = "FETCH_ALL_PRODUCT_GROUP";
export const FETCH_ALL_SIZE = "FETCH_ALL_SIZE";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const FETCH_ALL_PRODUCT = "FETCH_ALL_PRODUCT";
export const UPDATE_MAIN_AREA = "UPDATE_MAIN_AREA";
export const CREATE_PRODUCT_GROUP = "CREATE_PRODUCT_GROUP";
export const UPDATE_PRODUCT_GROUP = "UPDATE_PRODUCT_GROUP";
export const UPDATE_SIZE = "UPDATE_SIZE";
export const CREATE_SIZE = "CREATE_SIZE";
export const DELETE_SIZE = "DELETE_SIZE";

export const DELETE_CUSTOMER = "DELETE_CUSTOMER";